name: 'Setup node, pnpm, and cache'
inputs:
  node_version:
    required: false
    default: '22.x'

runs:
  using: 'composite'
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Set up Node ${{ inputs.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile
        pnpm run prisma:generate
      env:
        HUSKY: '0'
